# Generated by Django 4.2.9 on 2024-03-09 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255, unique=True)),
                ('epic_number', models.IntegerField()),
                ('password', models.IntegerField()),
            ],
            options={
                'db_table': 'voters',
            },
        ),
    ]
